export const europeanCountries = [
  { name: "Albania", slug: "albania" },
  { name: "Andorra", slug: "andorra" },
  { name: "Austria", slug: "austria" },
  { name: "Belarus", slug: "belarus" },
  { name: "Belgium", slug: "belgium" },
  { name: "Bosnia and Herzegovina", slug: "bosnia-and-herzegovina" },
  { name: "Bulgaria", slug: "bulgaria" },
  { name: "Croatia", slug: "croatia" },
  { name: "Cyprus", slug: "cyprus" },
  { name: "Czechia", slug: "czechia" },
  { name: "Denmark", slug: "denmark" },
  { name: "Estonia", slug: "estonia" },
  { name: "Finland", slug: "finland" },
  { name: "France", slug: "france" },
  { name: "Germany", slug: "germany" },
  { name: "Greece", slug: "greece" },
  { name: "Hungary", slug: "hungary" },
  { name: "Iceland", slug: "iceland" },
  { name: "Ireland", slug: "ireland" },
  { name: "Italy", slug: "italy" },
  { name: "Kosovo", slug: "kosovo" },
  { name: "Latvia", slug: "latvia" },
  { name: "Liechtenstein", slug: "liechtenstein" },
  { name: "Lithuania", slug: "lithuania" },
  { name: "Luxembourg", slug: "luxembourg" },
  { name: "Malta", slug: "malta" },
  { name: "Moldova", slug: "moldova" },
  { name: "Monaco", slug: "monaco" },
  { name: "Montenegro", slug: "montenegro" },
  { name: "Netherlands", slug: "netherlands" },
  { name: "North Macedonia", slug: "north-macedonia" },
  { name: "Norway", slug: "norway" },
  { name: "Poland", slug: "poland" },
  { name: "Portugal", slug: "portugal" },
  { name: "Romania", slug: "romania" },
  { name: "San Marino", slug: "san-marino" },
  { name: "Serbia", slug: "serbia" },
  { name: "Slovakia", slug: "slovakia" },
  { name: "Slovenia", slug: "slovenia" },
  { name: "Spain", slug: "spain" },
  { name: "Sweden", slug: "sweden" },
  { name: "Switzerland", slug: "switzerland" },
  { name: "Turkey", slug: "turkey" },
  { name: "Ukraine", slug: "ukraine" },
  { name: "United Kingdom", slug: "united-kingdom" },
  { name: "Vatican City", slug: "vatican-city" }
];
